---
# Custom Terminal theme.
- name: Terminal | Get current Terminal profile.
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  always_run: yes

- name: Terminal | Ensure custom Terminal profile is added.
  shell: open files/terminal/JJG-Term.terminal
  changed_when: false
  when: "'JJG-Term' not in terminal_theme.stdout"

- name: Terminal | Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string JJG-Term
    - defaults write com.apple.terminal 'Startup Window Settings' -string JJG-Term
  changed_when: false
  when: "'JJG-Term' not in terminal_theme.stdout"

# Sudoers configuration (enables more convenient Vagrant usage).
- name: Copy sudoers configuration into place.
  become: yes
  become_user: root
  copy:
    src: files/etc/sudoers
    dest: /etc/sudoers
    mode: 0440
    validate: 'visudo -cf %s'
  become: yes
  when: configure_sudoers
  ignore_errors: yes
